// Level 6 Lesson Content - Bilingual (Hindi default + English)
// Proper nouns NOT to translate: Rohit, Priya, Stock, Share, Index, Nifty, Sensex, IPO, SIP, Mutual Fund

import { BilingualLessonContent } from "./types";

export const level6Bilingual: BilingualLessonContent = {
  hi: {
    level: 6,
    lessonId: "level-6-trading-strategies",
    title: "Level 6: Trading Strategies – Soch Samajh Ke Trade Karo",
    subtitle: "Bina strategy ke trading gambling hai",
    scenes: [
      {
        id: "scene-1",
        type: "scene",
        title: "Rohit ka Excitement",
        speaker: "narrator",
        content: [
          "Rohit ne charts dekhna seekh liya hai.",
          "Ab usse lagta hai ki wo trading ke liye ready hai.",
          "Wo Priya ke paas excited hokar aata hai.",
        ],
      },
      {
        id: "scene-1-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Priya! Maine charts samajh liye!",
          "Ab main trading shuru kar sakta hoon, right?",
          "Kal hi ek stock bahut achha lag raha tha!",
        ],
      },
      {
        id: "scene-2-priya",
        type: "scene",
        title: "Priya ka Reality Check",
        speaker: "priya",
        content: [
          "Rohit, ruko. Ek important sawaal hai.",
          "Tum wo stock kab kharidoge, kab bechoge,",
          "aur agar galat ho gaye toh kya karoge?",
        ],
      },
      {
        id: "scene-2-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Hmm... wo toh maine socha nahi...",
          "Jab profit dikhe tab bech dunga!",
        ],
      },
      {
        id: "scene-3-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Yahi sabse badi galti hai beginners ki.",
          "\"Jab dikhega tab dekhenge\" – ye approach kaam nahi karti.",
          "Trading ke liye PEHLE se plan chahiye.",
        ],
      },
      {
        id: "concept-1",
        type: "concept",
        title: "Trading Strategy ka Matlab Kya Hai?",
        content: [
          "Strategy matlab: PEHLE se decide karna:",
          "",
          "1. Entry: Kab kharidna hai? (Kis price pe, kis signal pe)",
          "2. Exit: Kab bechna hai? (Profit pe ya loss pe)",
          "3. Risk: Kitna loss afford kar sakte ho?",
          "4. Wait: Kab trade NAHI karna hai?",
          "",
          "Agar ye 4 cheezein clear nahi, toh wo trading nahi – gambling hai.",
        ],
      },
      {
        id: "scene-4-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Matlab har trade se pehle ye 4 sawaal poochne chahiye?",
        ],
      },
      {
        id: "scene-4-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Bilkul! Aur agar in sawaalon ka jawab nahi hai,",
          "toh us din trade mat karo. Simple.",
        ],
      },
      {
        id: "concept-2",
        type: "concept",
        title: "Delivery vs Intraday – Kya Farak Hai?",
        content: [
          "Delivery Trading:",
          "- Stock kharidke rakho (days, weeks, months)",
          "- Patience chahiye, lekin risk kam",
          "- Beginners ke liye suitable",
          "",
          "Intraday Trading:",
          "- Usi din kharido aur becho",
          "- Fast decisions, zyada risk",
          "- Beginners ke liye NAHI recommend",
          "",
          "Rohit, tum pehle Delivery se shuru karo.",
        ],
      },
      {
        id: "scene-5-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Matlab Intraday me jaldi paisa banta hai?",
        ],
      },
      {
        id: "scene-5-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Jaldi jaata bhi hai! 90% intraday traders loss me rehte hain.",
          "Pehle delivery me practice karo, discipline seekho.",
        ],
      },
      {
        id: "concept-3",
        type: "concept",
        title: "Trend Following – Simple Strategy",
        content: [
          "Trend matlab: Market kis direction me ja rahi hai?",
          "",
          "- Agar market upar ja rahi hai (uptrend) – buy karo",
          "- Agar market neeche ja rahi hai (downtrend) – wait karo ya avoid karo",
          "",
          "\"Trend is your friend\" – ye purani kahawat sach hai.",
          "Beginners ko HAMESHA trend ke saath trade karna chahiye,",
          "uske against nahi.",
        ],
      },
      {
        id: "scene-6-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Matlab agar Nifty gir raha hai, toh main buy nahi karunga?",
        ],
      },
      {
        id: "scene-6-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Sahi samjhe! Falling market me beginners ko side me rehna chahiye.",
          "Trend badalte hi opportunity aayegi.",
        ],
      },
      {
        id: "concept-4",
        type: "concept",
        title: "Support & Resistance – Basic Levels",
        content: [
          "Support: Wo price jahan stock girna band karta hai",
          "(Buyers strong hote hain)",
          "",
          "Resistance: Wo price jahan stock upar jaana band karta hai",
          "(Sellers strong hote hain)",
          "",
          "Simple rule:",
          "- Support ke paas buy karo (achha entry point)",
          "- Resistance ke paas sell karo ya wait karo",
        ],
      },
      {
        id: "scene-7-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Ye toh chart dekhke samajh aa sakta hai!",
        ],
      },
      {
        id: "scene-7-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Haan! Lekin yaad rakhna – ye guarantee nahi hai.",
          "Support toot bhi sakta hai. Isliye stop-loss zaroor lagao.",
        ],
      },
      {
        id: "concept-5",
        type: "concept",
        title: "Risk-Reward Thinking – Sabse Important",
        content: [
          "Har trade me ye socho:",
          "",
          "\"Agar main Rs. 100 risk le raha hoon,",
          "toh mujhe kam se kam Rs. 200-300 ka target chahiye.\"",
          "",
          "Risk-Reward Ratio: 1:2 ya 1:3",
          "",
          "Agar risk zyada aur reward kam hai – wo trade mat lo.",
          "Patience rakho, achhe setup ka wait karo.",
        ],
      },
      {
        id: "scene-8-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Matlab har trade lene ki zaroorat nahi!",
        ],
      },
      {
        id: "scene-8-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Exactly! Best traders kam trades lete hain, lekin quality trades.",
          "Overtrading se bachna bahut zaroori hai.",
        ],
      },
      {
        id: "concept-6",
        type: "concept",
        title: "Discipline > Prediction",
        content: [
          "Bahut log sochte hain trading = future predict karna.",
          "Lekin sach ye hai:",
          "",
          "Trading = Apne rules follow karna.",
          "",
          "- Jo plan banaya, usko follow karo",
          "- Emotions me aakar plan mat badlo",
          "- Loss ho gaya toh bhi rule follow karo",
          "",
          "Prediction galat ho sakti hai,",
          "lekin discipline se long-term me profit hota hai.",
        ],
      },
      {
        id: "scene-9-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Ab samajh aaya! Strategy aur discipline pehle,",
          "profit baad me aayega.",
        ],
      },
      {
        id: "scene-9-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Yahi asli trading mindset hai, Rohit!",
          "Ab tum ready ho apna pehla plan banana.",
        ],
      },
      {
        id: "summary",
        type: "summary",
        title: "Is Level Me Aapne Kya Seekha",
        content: [
          "Trading Strategy ka matlab: Entry, Exit, Risk, Wait",
          "Delivery vs Intraday – beginners ke liye Delivery better",
          "Trend Following – trend ke saath trade karo",
          "Support & Resistance – basic levels samjho",
          "Risk-Reward Thinking – 1:2 ya better",
          "Discipline > Prediction – rules follow karo",
        ],
      },
      {
        id: "teaser",
        type: "scene",
        title: "Next Level Teaser",
        speaker: "narrator",
        content: [
          "Strategy toh aa gayi, lekin jab loss hota hai tab emotions kabu me kaise rakhein?",
          "Fear aur greed ko kaise manage karein?",
          "",
          "Level 7 me jaano: Risk Control & Trader Psychology",
        ],
      },
    ],
  },
  en: {
    level: 6,
    lessonId: "level-6-trading-strategies",
    title: "Level 6: Trading Strategies – Trade with a Plan",
    subtitle: "Trading without strategy is gambling",
    scenes: [
      {
        id: "scene-1",
        type: "scene",
        title: "Rohit's Excitement",
        speaker: "narrator",
        content: [
          "Rohit has learned to read charts.",
          "He now feels ready to start trading.",
          "He comes to Priya, excited.",
        ],
      },
      {
        id: "scene-1-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Priya! I understood charts!",
          "I can start trading now, right?",
          "There was a stock that looked really good yesterday!",
        ],
      },
      {
        id: "scene-2-priya",
        type: "scene",
        title: "Priya's Reality Check",
        speaker: "priya",
        content: [
          "Rohit, wait. There's an important question.",
          "When will you buy that stock, when will you sell,",
          "and what will you do if you're wrong?",
        ],
      },
      {
        id: "scene-2-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Hmm... I didn't think about that...",
          "I'll sell when I see profit!",
        ],
      },
      {
        id: "scene-3-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "This is the biggest mistake beginners make.",
          "\"We'll see when it happens\" – this approach doesn't work.",
          "Trading needs a plan BEFOREHAND.",
        ],
      },
      {
        id: "concept-1",
        type: "concept",
        title: "What Does Trading Strategy Mean?",
        content: [
          "Strategy means: Deciding BEFOREHAND:",
          "",
          "1. Entry: When to buy? (At what price, on what signal)",
          "2. Exit: When to sell? (At profit or at loss)",
          "3. Risk: How much loss can you afford?",
          "4. Wait: When NOT to trade?",
          "",
          "If these 4 things aren't clear, it's not trading – it's gambling.",
        ],
      },
      {
        id: "scene-4-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "So I should ask these 4 questions before every trade?",
        ],
      },
      {
        id: "scene-4-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Exactly! And if you don't have answers to these questions,",
          "don't trade that day. Simple.",
        ],
      },
      {
        id: "concept-2",
        type: "concept",
        title: "Delivery vs Intraday – What's the Difference?",
        content: [
          "Delivery Trading:",
          "- Buy and hold stock (days, weeks, months)",
          "- Needs patience, but lower risk",
          "- Suitable for beginners",
          "",
          "Intraday Trading:",
          "- Buy and sell on the same day",
          "- Fast decisions, higher risk",
          "- NOT recommended for beginners",
          "",
          "Rohit, start with Delivery first.",
        ],
      },
      {
        id: "scene-5-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "So money is made faster in Intraday?",
        ],
      },
      {
        id: "scene-5-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Lost faster too! 90% of intraday traders are in loss.",
          "First practice in Delivery, learn discipline.",
        ],
      },
      {
        id: "concept-3",
        type: "concept",
        title: "Trend Following – Simple Strategy",
        content: [
          "Trend means: Which direction is the market going?",
          "",
          "- If market is going up (uptrend) – buy",
          "- If market is going down (downtrend) – wait or avoid",
          "",
          "\"Trend is your friend\" – this old saying is true.",
          "Beginners should ALWAYS trade with the trend,",
          "not against it.",
        ],
      },
      {
        id: "scene-6-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "So if Nifty is falling, I won't buy?",
        ],
      },
      {
        id: "scene-6-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Right! In a falling market, beginners should stay on the sidelines.",
          "Opportunity will come when the trend changes.",
        ],
      },
      {
        id: "concept-4",
        type: "concept",
        title: "Support & Resistance – Basic Levels",
        content: [
          "Support: The price where a stock stops falling",
          "(Buyers are strong)",
          "",
          "Resistance: The price where a stock stops rising",
          "(Sellers are strong)",
          "",
          "Simple rule:",
          "- Buy near Support (good entry point)",
          "- Sell near Resistance or wait",
        ],
      },
      {
        id: "scene-7-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "This can be understood by looking at the chart!",
        ],
      },
      {
        id: "scene-7-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Yes! But remember – this isn't a guarantee.",
          "Support can break. That's why always use stop-loss.",
        ],
      },
      {
        id: "concept-5",
        type: "concept",
        title: "Risk-Reward Thinking – Most Important",
        content: [
          "Think this before every trade:",
          "",
          "\"If I'm risking Rs. 100,",
          "I should target at least Rs. 200-300.\"",
          "",
          "Risk-Reward Ratio: 1:2 or 1:3",
          "",
          "If risk is high and reward is low – don't take that trade.",
          "Be patient, wait for a good setup.",
        ],
      },
      {
        id: "scene-8-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "So I don't need to take every trade!",
        ],
      },
      {
        id: "scene-8-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Exactly! Best traders take fewer trades, but quality trades.",
          "Avoiding overtrading is very important.",
        ],
      },
      {
        id: "concept-6",
        type: "concept",
        title: "Discipline > Prediction",
        content: [
          "Many people think trading = predicting the future.",
          "But the truth is:",
          "",
          "Trading = Following your rules.",
          "",
          "- Follow the plan you made",
          "- Don't change the plan based on emotions",
          "- Even if you lose, follow the rule",
          "",
          "Prediction can be wrong,",
          "but discipline leads to long-term profit.",
        ],
      },
      {
        id: "scene-9-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Now I understand! Strategy and discipline first,",
          "profit will come later.",
        ],
      },
      {
        id: "scene-9-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "This is the real trading mindset, Rohit!",
          "Now you're ready to make your first plan.",
        ],
      },
      {
        id: "summary",
        type: "summary",
        title: "What You Learned in This Level",
        content: [
          "Trading Strategy means: Entry, Exit, Risk, Wait",
          "Delivery vs Intraday – Delivery is better for beginners",
          "Trend Following – trade with the trend",
          "Support & Resistance – understand basic levels",
          "Risk-Reward Thinking – 1:2 or better",
          "Discipline > Prediction – follow your rules",
        ],
      },
      {
        id: "teaser",
        type: "scene",
        title: "Next Level Teaser",
        speaker: "narrator",
        content: [
          "Strategy is in place, but how do you control emotions when you lose?",
          "How do you manage fear and greed?",
          "",
          "Find out in Level 7: Risk Control & Trader Psychology",
        ],
      },
    ],
  },
};
