// Level 8 Lesson Content - Bilingual (Hindi default + English)
// Proper nouns NOT to translate: Rohit, Priya, Stock, Share, Index, Nifty, Sensex, IPO, SIP, Mutual Fund

import { BilingualLessonContent } from "./types";

export const level8Bilingual: BilingualLessonContent = {
  hi: {
    level: 8,
    lessonId: "level-8-confident-investor",
    title: "Level 8: Confident Investor – Rohit ka Badlaav",
    subtitle: "Ab dar nahi, samajh hai. Ab tips nahi, plan hai.",
    scenes: [
      {
        id: "scene-1",
        type: "scene",
        title: "Rohit ka Transformation",
        speaker: "narrator",
        content: [
          "Kuch mahine pehle Rohit ko stock market se bahut dar lagta tha.",
          "Usne socha tha ki ye sirf ameer logon ka kaam hai.",
          "Aaj wo market ko samajhta hai. Uska nazariya badal chuka hai.",
        ],
      },
      {
        id: "scene-1-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Priya, yaad hai jab maine pehli baar trading ke baare me pucha tha?",
          "Tab mujhe lagta tha ki stock market ek lottery hai.",
          "Ab samajh aata hai – ye ek skill hai, jua nahi.",
        ],
      },
      {
        id: "scene-2-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Rohit, ye badlaav hi sabse badi cheez hai.",
          "Market se paise kamane se zyada important hai –",
          "market ko samajhna aur khud par control rakhna.",
        ],
      },
      {
        id: "scene-2-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Pehle mujhe loss se bahut dar lagta tha.",
          "Ab samajh aata hai – loss toh learning ka part hai.",
          "Important ye hai ki ek loss se doosri galti na ho.",
        ],
      },
      {
        id: "scene-3-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Bilkul! Aur ye baat bahut kam log samajhte hain.",
          "Market upar-neeche hota rahega – ye normal hai.",
          "Jo log panic karte hain, wo hi sabse zyada loss karte hain.",
        ],
      },
      {
        id: "concept-1",
        type: "concept",
        title: "Confident Investor ki 7 Habits",
        content: [
          "1. Plan ke Saath Invest Karta Hai",
          "   Random tips nahi follow karta, apna research karta hai.",
          "",
          "2. Goal-Based Sochta Hai",
          "   \"5 saal me ghar ka down payment\" – aisa clear goal rakhta hai.",
          "",
          "3. Risk Pehle Define Karta Hai",
          "   Trade lene se pehle – \"agar galat hua toh kitna loss sahega?\"",
          "",
          "4. Emotions Pe Control Rakhta Hai",
          "   Fear ya greed se decisions nahi leta.",
          "",
          "5. Har Din Trade Nahi Karta",
          "   Patience rakhta hai. Achha setup milne ka wait karta hai.",
          "",
          "6. Apna Record Rakhta Hai",
          "   Journal maintain karta hai – kya kiya, kyun kiya, kya seekha.",
          "",
          "7. Long-Term Sochta Hai",
          "   \"Aaj Rs. 1000 bane\" se zyada – \"5 saal me kya build hoga?\"",
        ],
      },
      {
        id: "scene-4-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Ye 7 habits mujhe yaad rakhni hain!",
          "Especially #5 – har din trade karna zaroori nahi.",
        ],
      },
      {
        id: "scene-4-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Haan! Bahut log ye galti karte hain.",
          "Wo sochte hain agar roz trade nahi kiya toh paise nahi banenge.",
          "Lekin reality ye hai – wrong trade se zyada nuksan hota hai.",
        ],
      },
      {
        id: "concept-2",
        type: "concept",
        title: "Goal-Based Investment Planning",
        content: [
          "Pehle goal decide karo, phir invest karo:",
          "",
          "Short-Term (1-2 saal):",
          "- Emergency fund banao (6 months expenses)",
          "- Low-risk options: FD, Liquid Funds",
          "",
          "Medium-Term (3-5 saal):",
          "- Ghar ka down payment, car, shaadi",
          "- Balanced approach: SIP + some stocks",
          "",
          "Long-Term (5+ saal):",
          "- Retirement, bachon ki padhai",
          "- Equity-heavy portfolio chalega",
          "",
          "Remember: Goal ke bina investing = random gambling",
        ],
      },
      {
        id: "scene-5-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Maine apna goal set kar liya hai.",
          "5 saal me emergency fund + ghar ka down payment.",
        ],
      },
      {
        id: "scene-5-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Bahut achha! Ab tu sirf paison ke peeche nahi bhaag raha,",
          "balki ek purpose ke saath invest kar raha hai.",
        ],
      },
      {
        id: "concept-3",
        type: "concept",
        title: "Emotion-Controlled Decisions",
        content: [
          "Jab Market Girta Hai:",
          "- Panic sell mat karo",
          "- Achhi companies aur cheaper ho gayi – opportunity dekho",
          "- Apne plan pe stick karo",
          "",
          "Jab Market Chadta Hai:",
          "- Overconfident mat ho jao",
          "- Profit booking bhi zaroori hai",
          "- Greed se bachke raho",
          "",
          "Simple Rule: Decisions pehle se likh ke rakhke",
          "Jab emotions high ho, toh list dekho, mann ki mat suno.",
        ],
      },
      {
        id: "scene-6-priya",
        type: "scene",
        title: "Priya ka Final Message",
        speaker: "priya",
        content: [
          "Rohit, aaj main bahut khush hoon.",
          "Tune wo seekha jo bahut log saalon me nahi seekh paate.",
          "",
          "Yaad rakh:",
          "- Market kabhi tumhara dushman nahi hai",
          "- Tumhara sabse bada dushman tumhari apni impatience hai",
          "- Discipline se bade profits aate hain, tips se nahi",
          "",
          "Ab tu ek Confident Investor hai.",
        ],
      },
      {
        id: "scene-6-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Thank you Priya!",
          "Pehle mujhe lagta tha main kabhi ye sab nahi samajh paunga.",
          "Ab lagta hai – main bhi kar sakta hoon, step by step.",
        ],
      },
      {
        id: "concept-4",
        type: "concept",
        title: "Ab Aap Kya Kar Sakte Hain",
        content: [
          "1. Apna Investment Goal Likho",
          "   Paper pe likho – kitna paisa, kitne saal me, kis kaam ke liye.",
          "",
          "2. Emergency Fund Pehle Banao",
          "   Minimum 3-6 months expenses ka fund rakhna zaroori hai.",
          "",
          "3. Paper Trading Se Shuru Karo",
          "   Real money lagane se pehle practice karo.",
          "",
          "4. Small Amount Se Start Karo",
          "   Jo paisa 2-3 saal tak chahiye nahi, wahi invest karo.",
          "",
          "5. Journal Maintain Karo",
          "   Har trade/investment ko note karo – kyun liya, kyun exit kiya.",
          "",
          "6. Courses Revise Karte Raho",
          "   Seekhna kabhi band mat karo. Market badalta hai, tum bhi badlo.",
        ],
      },
      {
        id: "scene-7-narrator",
        type: "scene",
        speaker: "narrator",
        content: [
          "Rohit ki journey yahan khatam nahi hoti.",
          "Ye toh sirf shuruaat hai.",
          "",
          "Aur tumhari journey bhi aaj se shuru ho sakti hai.",
          "Tumhe sirf ek cheez yaad rakhni hai:",
          "",
          "\"Main bhi Rohit jaise seekh sakta hoon.\"",
        ],
      },
      {
        id: "summary",
        type: "summary",
        title: "Is Level Me Aapne Kya Seekha",
        content: [
          "Confident investor ka matlab – plan follow karna, tips nahi",
          "7 important habits of successful investors",
          "Goal-based investment planning kaise karein",
          "Emotions ko control kaise rakhein",
          "Long-term soch hi real success hai",
          "Action plan – kya karna hai ab",
        ],
      },
      {
        id: "closing",
        type: "scene",
        title: "Journey Complete",
        speaker: "narrator",
        content: [
          "Congratulations! Aapne apni learning journey complete kar li.",
          "",
          "Yaad rakhna – ye sirf knowledge hai.",
          "Asli learning tab hogi jab tum apply karoge.",
          "",
          "All the best for your investing journey!",
        ],
      },
    ],
  },
  en: {
    level: 8,
    lessonId: "level-8-confident-investor",
    title: "Level 8: Confident Investor – Rohit's Transformation",
    subtitle: "No more fear, now there's understanding. No more tips, now there's a plan.",
    scenes: [
      {
        id: "scene-1",
        type: "scene",
        title: "Rohit's Transformation",
        speaker: "narrator",
        content: [
          "A few months ago, Rohit was very scared of the stock market.",
          "He thought it was only for rich people.",
          "Today he understands the market. His perspective has changed.",
        ],
      },
      {
        id: "scene-1-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Priya, remember when I first asked about trading?",
          "Back then I thought stock market was a lottery.",
          "Now I understand – it's a skill, not gambling.",
        ],
      },
      {
        id: "scene-2-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Rohit, this transformation is the biggest achievement.",
          "More important than making money from market is –",
          "understanding the market and keeping control over yourself.",
        ],
      },
      {
        id: "scene-2-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Earlier I was very scared of losses.",
          "Now I understand – loss is part of learning.",
          "Important is that one loss shouldn't lead to another mistake.",
        ],
      },
      {
        id: "scene-3-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Exactly! And very few people understand this.",
          "Market will keep going up and down – this is normal.",
          "Those who panic are the ones who lose the most.",
        ],
      },
      {
        id: "concept-1",
        type: "concept",
        title: "7 Habits of a Confident Investor",
        content: [
          "1. Invests with a Plan",
          "   Doesn't follow random tips, does own research.",
          "",
          "2. Thinks Goal-Based",
          "   \"Down payment for house in 5 years\" – has clear goals like this.",
          "",
          "3. Defines Risk First",
          "   Before taking trade – \"if wrong, how much loss can I bear?\"",
          "",
          "4. Controls Emotions",
          "   Doesn't make decisions based on fear or greed.",
          "",
          "5. Doesn't Trade Every Day",
          "   Has patience. Waits for good setup.",
          "",
          "6. Keeps Records",
          "   Maintains journal – what did, why did, what learned.",
          "",
          "7. Thinks Long-Term",
          "   More than \"made Rs. 1000 today\" – \"what will build in 5 years?\"",
        ],
      },
      {
        id: "scene-4-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "I need to remember these 7 habits!",
          "Especially #5 – trading every day isn't necessary.",
        ],
      },
      {
        id: "scene-4-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Yes! Many people make this mistake.",
          "They think if they don't trade daily, they won't make money.",
          "But reality is – wrong trades cause more damage.",
        ],
      },
      {
        id: "concept-2",
        type: "concept",
        title: "Goal-Based Investment Planning",
        content: [
          "First decide the goal, then invest:",
          "",
          "Short-Term (1-2 years):",
          "- Build emergency fund (6 months expenses)",
          "- Low-risk options: FD, Liquid Funds",
          "",
          "Medium-Term (3-5 years):",
          "- House down payment, car, wedding",
          "- Balanced approach: SIP + some stocks",
          "",
          "Long-Term (5+ years):",
          "- Retirement, children's education",
          "- Equity-heavy portfolio is fine",
          "",
          "Remember: Investing without goal = random gambling",
        ],
      },
      {
        id: "scene-5-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "I've set my goal.",
          "Emergency fund + house down payment in 5 years.",
        ],
      },
      {
        id: "scene-5-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Excellent! Now you're not just chasing money,",
          "you're investing with a purpose.",
        ],
      },
      {
        id: "concept-3",
        type: "concept",
        title: "Emotion-Controlled Decisions",
        content: [
          "When Market Falls:",
          "- Don't panic sell",
          "- Good companies just got cheaper – see the opportunity",
          "- Stick to your plan",
          "",
          "When Market Rises:",
          "- Don't get overconfident",
          "- Profit booking is also important",
          "- Stay away from greed",
          "",
          "Simple Rule: Write down decisions beforehand",
          "When emotions are high, look at the list, don't listen to your heart.",
        ],
      },
      {
        id: "scene-6-priya",
        type: "scene",
        title: "Priya's Final Message",
        speaker: "priya",
        content: [
          "Rohit, I'm very happy today.",
          "You learned what many people can't learn in years.",
          "",
          "Remember:",
          "- Market is never your enemy",
          "- Your biggest enemy is your own impatience",
          "- Big profits come from discipline, not tips",
          "",
          "Now you're a Confident Investor.",
        ],
      },
      {
        id: "scene-6-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Thank you Priya!",
          "Earlier I thought I could never understand all this.",
          "Now I feel – I can do it too, step by step.",
        ],
      },
      {
        id: "concept-4",
        type: "concept",
        title: "What You Can Do Now",
        content: [
          "1. Write Your Investment Goal",
          "   Write on paper – how much money, in how many years, for what purpose.",
          "",
          "2. Build Emergency Fund First",
          "   Minimum 3-6 months expenses fund is necessary.",
          "",
          "3. Start with Paper Trading",
          "   Practice before putting real money.",
          "",
          "4. Start with Small Amount",
          "   Invest only money you don't need for 2-3 years.",
          "",
          "5. Maintain a Journal",
          "   Note every trade/investment – why bought, why exited.",
          "",
          "6. Keep Revising Courses",
          "   Never stop learning. Market changes, you should change too.",
        ],
      },
      {
        id: "scene-7-narrator",
        type: "scene",
        speaker: "narrator",
        content: [
          "Rohit's journey doesn't end here.",
          "This is just the beginning.",
          "",
          "And your journey can also start from today.",
          "You just need to remember one thing:",
          "",
          "\"I can also learn like Rohit.\"",
        ],
      },
      {
        id: "summary",
        type: "summary",
        title: "What You Learned in This Level",
        content: [
          "Confident investor means – following plan, not tips",
          "7 important habits of successful investors",
          "How to do goal-based investment planning",
          "How to control emotions",
          "Long-term thinking is real success",
          "Action plan – what to do now",
        ],
      },
      {
        id: "closing",
        type: "scene",
        title: "Journey Complete",
        speaker: "narrator",
        content: [
          "Congratulations! You've completed your learning journey.",
          "",
          "Remember – this is just knowledge.",
          "Real learning will happen when you apply it.",
          "",
          "All the best for your investing journey!",
        ],
      },
    ],
  },
};
