// Level 7 Lesson Content - Bilingual (Hindi default + English)
// Proper nouns NOT to translate: Rohit, Priya, Stock, Share, Index, Nifty, Sensex, IPO, SIP, Mutual Fund

import { BilingualLessonContent } from "./types";

export const level7Bilingual: BilingualLessonContent = {
  hi: {
    level: 7,
    lessonId: "level-7-trader-psychology",
    title: "Level 7: Trader Psychology – Dimaag Jeetna Seekho",
    subtitle: "Sabse bada enemy market nahi, tumhara mann hai",
    scenes: [
      {
        id: "scene-1",
        type: "scene",
        title: "Rohit ki Galti",
        speaker: "narrator",
        content: [
          "Rohit ne basics seekh liye. Strategy bhi samajh li.",
          "Usne apna pehla trade kiya... aur profit bhi hua!",
          "Lekin phir kuch aisa hua jo usne expect nahi kiya tha.",
        ],
      },
      {
        id: "scene-1-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Priya, maine kal Rs. 2000 ka profit kiya!",
          "Aaj maine socha aur zyada kama lunga...",
          "Lekin aaj Rs. 5000 ka loss ho gaya.",
        ],
      },
      {
        id: "scene-2-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Rohit, ye bahut common galti hai.",
          "Kal profit hua, toh aaj overconfidence aa gaya.",
          "Aur jab loss hua, toh recover karne ke chakkar me aur zyada loss.",
        ],
      },
      {
        id: "scene-2-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Haan... maine socha jaldi se loss wapas kama lunga.",
          "Isliye bade trade liye. Galti ho gayi.",
        ],
      },
      {
        id: "scene-3-priya",
        type: "scene",
        title: "Priya ka Golden Rule",
        speaker: "priya",
        content: [
          "Rohit, ye samajh lo:",
          "Trading me sabse bada enemy market nahi hai.",
          "Sabse bada enemy tumhara APNA MANN hai.",
          "",
          "Fear, greed, impatience, overconfidence –",
          "ye sab tumhe galat decisions lene pe majboor karte hain.",
        ],
      },
      {
        id: "concept-1",
        type: "concept",
        title: "Revenge Trading – Sabse Khatarnak Galti",
        content: [
          "Jab loss hota hai, mann karta hai:",
          "\"Abhi turant recover kar lunga!\"",
          "",
          "Isko kehte hain Revenge Trading.",
          "",
          "Ye galti kyun khatarnak hai:",
          "- Emotions me decisions lete ho",
          "- Risk management bhool jaate ho",
          "- Chhota loss bada loss ban jata hai",
          "",
          "Rule: Loss ke baad break lo. Us din aur trade mat karo.",
        ],
      },
      {
        id: "scene-4-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Matlab loss ke baad screen band kar dena chahiye?",
        ],
      },
      {
        id: "scene-4-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Bilkul! Best traders loss ke baad walk lete hain.",
          "Fresh mind se next day better decision hota hai.",
        ],
      },
      {
        id: "concept-2",
        type: "concept",
        title: "Profit ke Baad Overconfidence",
        content: [
          "Jab profit hota hai, mann karta hai:",
          "\"Main toh expert ho gaya! Aur zyada kamata hoon!\"",
          "",
          "Ye feeling dangerous hai.",
          "",
          "Profit ke baad kya hota hai:",
          "- Position size badha dete ho",
          "- Rules todne lagte ho",
          "- Ek big loss saari gains kha jata hai",
          "",
          "Rule: Profit ke baad bhi same discipline rakho. Humble raho.",
        ],
      },
      {
        id: "scene-5-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Matlab jeet ke baad bhi control zaroori hai!",
        ],
      },
      {
        id: "scene-5-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Sahi pakde! Consistency sirf discipline se aati hai,",
          "ek-do lucky trades se nahi.",
        ],
      },
      {
        id: "concept-3",
        type: "concept",
        title: "Beginner Trader ki 5 Common Mental Mistakes",
        content: [
          "1. FOMO (Fear of Missing Out)",
          "   \"Sab kama rahe hain, main reh gaya!\"",
          "   – Jaldi me bina research trade karna",
          "",
          "2. Fear of Loss",
          "   \"Agar loss hua toh?\"",
          "   – Dar ki wajah se achhi opportunity miss karna",
          "",
          "3. Overtrading",
          "   \"Roz trade karna zaroori hai\"",
          "   – Bina setup ke trade lena = loss",
          "",
          "4. Comparing with Others",
          "   \"Wo Rs. 1 lakh kamaya, main kyun nahi?\"",
          "   – Har kisi ka capital aur risk alag hai",
          "",
          "5. Hoping & Praying",
          "   \"Shayad wapas aa jayega...\"",
          "   – Stop-loss na lagana = disaster",
        ],
      },
      {
        id: "scene-6-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Ye sab maine feel kiya hai!",
          "Especially FOMO aur comparison wala.",
        ],
      },
      {
        id: "scene-6-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Har beginner ye feel karta hai, Rohit.",
          "Important ye hai ki tum aware ho aur control karo.",
        ],
      },
      {
        id: "concept-4",
        type: "concept",
        title: "Simple Mental Rules for Beginners",
        content: [
          "1. Capital Protection > Profit",
          "   Pehle apna paisa bachao, profit baad me aayega.",
          "",
          "2. Process pe Focus, Result pe Nahi",
          "   Sahi process follow karo, results apne aap aayenge.",
          "",
          "3. No Trade is Also a Good Trade",
          "   Agar achha setup nahi hai, toh wait karo.",
          "   Patience ek skill hai.",
          "",
          "4. Apna Comparison Sirf Khud Se Karo",
          "   Kal se better ho aaj? Bas itna kaafi hai.",
        ],
      },
      {
        id: "scene-7-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Rohit, trading ek marathon hai, sprint nahi.",
          "Jo log jaldi ameer banne ki sochte hain,",
          "wo aksar jaldi gareeb ho jaate hain.",
        ],
      },
      {
        id: "scene-7-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Ab samajh aa raha hai.",
          "Trading sirf paisa nahi, khud ko samajhna bhi hai.",
        ],
      },
      {
        id: "concept-5",
        type: "concept",
        title: "Normal Salaried Person ke Liye Reality Check",
        content: [
          "Agar tum salaried ho:",
          "",
          "- Trading se salary replace karne ki soch mat rakho (abhi)",
          "- Extra income ki tarah dekho, main income ki tarah nahi",
          "- Sirf wo paisa invest karo jo 2-3 saal tak na chahiye",
          "- Paper trading se practice karo pehle",
          "",
          "Slow and steady wins the race.",
          "Jaldi ke chakkar me mat pado.",
        ],
      },
      {
        id: "scene-8-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Ye sahi hai. Main apni job bhi karunga,",
          "aur side me slowly trading seekhunga.",
        ],
      },
      {
        id: "scene-8-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Yahi mature approach hai!",
          "Tumhara mindset ab ek real investor jaisa ho raha hai.",
        ],
      },
      {
        id: "summary",
        type: "summary",
        title: "Is Level Me Aapne Kya Seekha",
        content: [
          "Sabse bada enemy market nahi, apna mann hai",
          "Revenge trading kyun dangerous hai",
          "Profit ke baad overconfidence se bachna",
          "5 common mental mistakes (FOMO, Fear, Overtrading, Comparison, Hoping)",
          "Simple mental rules – Capital protection, Process focus, No trade = good trade",
          "Salaried person ke liye practical advice",
        ],
      },
      {
        id: "teaser",
        type: "scene",
        title: "Final Level Teaser",
        speaker: "narrator",
        content: [
          "Ab tum basics, strategy, risk, aur psychology sab samajh gaye.",
          "Ab waqt aa gaya hai ek confident investor banne ka.",
          "",
          "Level 8: Confident Investor – Rohit ka Badlaav",
        ],
      },
    ],
  },
  en: {
    level: 7,
    lessonId: "level-7-trader-psychology",
    title: "Level 7: Trader Psychology – Learn to Win Your Mind",
    subtitle: "Your biggest enemy isn't the market, it's your own mind",
    scenes: [
      {
        id: "scene-1",
        type: "scene",
        title: "Rohit's Mistake",
        speaker: "narrator",
        content: [
          "Rohit learned the basics. He understood strategy too.",
          "He made his first trade... and even made a profit!",
          "But then something happened that he didn't expect.",
        ],
      },
      {
        id: "scene-1-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Priya, I made Rs. 2000 profit yesterday!",
          "Today I thought I'd earn even more...",
          "But today I lost Rs. 5000.",
        ],
      },
      {
        id: "scene-2-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Rohit, this is a very common mistake.",
          "Yesterday's profit gave you overconfidence.",
          "And when loss happened, you lost even more trying to recover.",
        ],
      },
      {
        id: "scene-2-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Yes... I thought I'd quickly recover the loss.",
          "So I took bigger trades. Made a mistake.",
        ],
      },
      {
        id: "scene-3-priya",
        type: "scene",
        title: "Priya's Golden Rule",
        speaker: "priya",
        content: [
          "Rohit, understand this:",
          "In trading, the biggest enemy isn't the market.",
          "The biggest enemy is your OWN MIND.",
          "",
          "Fear, greed, impatience, overconfidence –",
          "all of these force you to make wrong decisions.",
        ],
      },
      {
        id: "concept-1",
        type: "concept",
        title: "Revenge Trading – The Most Dangerous Mistake",
        content: [
          "When you have a loss, you feel:",
          "\"I'll recover it right now!\"",
          "",
          "This is called Revenge Trading.",
          "",
          "Why this mistake is dangerous:",
          "- You make decisions based on emotions",
          "- You forget risk management",
          "- Small loss becomes big loss",
          "",
          "Rule: Take a break after loss. Don't trade more that day.",
        ],
      },
      {
        id: "scene-4-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "So I should close the screen after a loss?",
        ],
      },
      {
        id: "scene-4-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Exactly! Best traders take a walk after a loss.",
          "Fresh mind leads to better decisions next day.",
        ],
      },
      {
        id: "concept-2",
        type: "concept",
        title: "Overconfidence After Profit",
        content: [
          "When you make a profit, you feel:",
          "\"I'm an expert now! Let me earn even more!\"",
          "",
          "This feeling is dangerous.",
          "",
          "What happens after profit:",
          "- You increase position size",
          "- You start breaking rules",
          "- One big loss eats all gains",
          "",
          "Rule: Maintain same discipline after profit too. Stay humble.",
        ],
      },
      {
        id: "scene-5-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "So control is needed even after winning!",
        ],
      },
      {
        id: "scene-5-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Exactly right! Consistency comes from discipline,",
          "not from one or two lucky trades.",
        ],
      },
      {
        id: "concept-3",
        type: "concept",
        title: "5 Common Mental Mistakes of Beginner Traders",
        content: [
          "1. FOMO (Fear of Missing Out)",
          "   \"Everyone's earning, I'm left behind!\"",
          "   – Trading without research in a hurry",
          "",
          "2. Fear of Loss",
          "   \"What if I lose?\"",
          "   – Missing good opportunities due to fear",
          "",
          "3. Overtrading",
          "   \"I need to trade every day\"",
          "   – Trading without setup = loss",
          "",
          "4. Comparing with Others",
          "   \"He made Rs. 1 lakh, why not me?\"",
          "   – Everyone's capital and risk is different",
          "",
          "5. Hoping & Praying",
          "   \"Maybe it will come back...\"",
          "   – Not using stop-loss = disaster",
        ],
      },
      {
        id: "scene-6-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "I've felt all of these!",
          "Especially FOMO and comparison.",
        ],
      },
      {
        id: "scene-6-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Every beginner feels this, Rohit.",
          "What's important is that you're aware and in control.",
        ],
      },
      {
        id: "concept-4",
        type: "concept",
        title: "Simple Mental Rules for Beginners",
        content: [
          "1. Capital Protection > Profit",
          "   First protect your money, profit will come later.",
          "",
          "2. Focus on Process, Not Result",
          "   Follow the right process, results will come automatically.",
          "",
          "3. No Trade is Also a Good Trade",
          "   If there's no good setup, wait.",
          "   Patience is a skill.",
          "",
          "4. Compare Only with Yourself",
          "   Are you better today than yesterday? That's enough.",
        ],
      },
      {
        id: "scene-7-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "Rohit, trading is a marathon, not a sprint.",
          "Those who think of getting rich quickly,",
          "often become poor quickly.",
        ],
      },
      {
        id: "scene-7-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "Now I'm understanding.",
          "Trading isn't just about money, it's about understanding yourself too.",
        ],
      },
      {
        id: "concept-5",
        type: "concept",
        title: "Reality Check for Normal Salaried Person",
        content: [
          "If you're salaried:",
          "",
          "- Don't think about replacing salary with trading (for now)",
          "- See it as extra income, not main income",
          "- Only invest money you don't need for 2-3 years",
          "- Practice with paper trading first",
          "",
          "Slow and steady wins the race.",
          "Don't fall for quick money schemes.",
        ],
      },
      {
        id: "scene-8-rohit",
        type: "scene",
        speaker: "rohit",
        content: [
          "This is right. I'll continue my job,",
          "and slowly learn trading on the side.",
        ],
      },
      {
        id: "scene-8-priya",
        type: "scene",
        speaker: "priya",
        content: [
          "This is the mature approach!",
          "Your mindset is now becoming like a real investor.",
        ],
      },
      {
        id: "summary",
        type: "summary",
        title: "What You Learned in This Level",
        content: [
          "Biggest enemy isn't market, it's your own mind",
          "Why revenge trading is dangerous",
          "Avoiding overconfidence after profit",
          "5 common mental mistakes (FOMO, Fear, Overtrading, Comparison, Hoping)",
          "Simple mental rules – Capital protection, Process focus, No trade = good trade",
          "Practical advice for salaried person",
        ],
      },
      {
        id: "teaser",
        type: "scene",
        title: "Final Level Teaser",
        speaker: "narrator",
        content: [
          "Now you understand basics, strategy, risk, and psychology.",
          "Now it's time to become a confident investor.",
          "",
          "Level 8: Confident Investor – Rohit's Transformation",
        ],
      },
    ],
  },
};
