export const styleGuide = {
  language: {
    default: "hinglish",
    structure: "70% Hindi + 30% English finance words",
    allowedEnglishWords: [
      "SIP",
      "Lumpsum", 
      "Stock Market",
      "Risk",
      "Returns",
      "Portfolio",
      "Diversification",
      "Goal",
      "Investing",
      "Trading",
      "Long-term",
      "Mutual Fund",
      "Index",
      "IPO",
      "Demat",
      "Broker",
      "Chart",
      "Profit",
      "Loss",
      "Entry",
      "Exit",
      "Strategy",
      "Beginner",
      "Expert",
      "FREE",
      "Course",
      "Calculator",
    ],
  },
  tone: {
    style: "friendly, beginner-focused",
    sentences: "short and simple",
    avoid: ["jargon", "complex terms", "full English paragraphs"],
  },
  characters: {
    priya: {
      role: "Expert Guide",
      roleHi: "Expert Guide (Dost)",
      personality: "helpful, encouraging, patient teacher",
    },
    rohit: {
      role: "Fellow Learner",
      roleHi: "Saath Seekhne Wala (Dost)",
      personality: "curious beginner, asks questions users might have",
    },
  },
} as const;
